services:
  db_chema:
    image: postgres:15-alpine
    container_name: nextjs_db_chema
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/3-migrate.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/4-reports.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/9-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/99-roles.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${APP_DB_USER}:${APP_DB_PASSWORD}@db_chema:5432/${POSTGRES_DB}
    depends_on:
      db_chema:
        condition: service_healthy